### PR TITLE
Defactor: remove TypeScript, native classes / decorators, ember-concurrency

### LINKED ISSUE #2: Uncaught TypeError: params is not iterable
Hi, 

I have tried to create a project by using the latest ember-cli (3.5.0), ember-engines (0.5.24) and the 0.1.0 version of this addon. It will throw this error message, and do you know how can I fix this?

Thanks

### LINKED ISSUE #3: Element descriptor's .kind property "undefined" on Ember 3.6
Hey there,
Just reporting a problem with lazy-mount on a freshly updated Ember 3.6 application. Using the standard ember-engines `{{mount}}` on a non-lazy loaded engine, I get no errors. Using `{{lazy-mount}}`, though, I get this:
```
[Error] TypeError: An element descriptor's .kind property must be either "method" or "field", but a decorator created an element descriptor with .kind "undefined"
	_toElementDescriptor (vendor.js:211257:315)
	_toElementFinisherExtras (vendor.js:211259:89)
	_decorateElement (vendor.js:211249:364)
	(funzione anonima) (vendor.js:211245:383)
	forEach
	_decorateClass (vendor.js:211245:252)
	_decorate (vendor.js:211227:197)
	(funzione anonima) (vendor.js:211285)
	exports (vendor.js:111)
	_reify (vendor.js:148)
	reify (vendor.js:135)
	exports (vendor.js:109)
	requireModule (vendor.js:32)
	_extractDefaultExport (vendor.js:221754)
	resolveOther (vendor.js:221433)
	resolve (vendor.js:221495)
	resolve (vendor.js:32926)
	resolve (vendor.js:32556)
	resolve (vendor.js:32558)
	factoryFor (vendor.js:32213)
	lookupComponentPair (vendor.js:58709)
	_lookupComponentDefinition (vendor.js:40054)
	lookupComponentHandle (vendor.js:39920)
	refineBlockSyntax (vendor.js:39781)
	compile (vendor.js:66820)
	compileBlock (vendor.js:67260)
	compileBlock (vendor.js:67624)
	(funzione anonima) (vendor.js:66691)
	compile (vendor.js:66569)
	compile (vendor.js:67127)
	compile (vendor.js:67100)
	getLayout (vendor.js:36588)
	(funzione anonima) (vendor.js:70522)
	evaluate (vendor.js:69516)
	evaluateSyscall (vendor.js:71656)
	evaluateInner (vendor.js:71630)
	evaluateOuter (vendor.js:71623)
	next (vendor.js:73120)
	execute (vendor.js:73110)
	handleException (vendor.js:72275)
	handleException (vendor.js:72398)
	throw (vendor.js:72222)
	evaluate (vendor.js:70031)
	execute (vendor.js:72209)
	rerender (vendor.js:72413)
	runInTransaction (vendor.js:41509)
	runInTransaction
	_renderRoots (vendor.js:37592:91)
	_renderRootsTransaction (vendor.js:37623)
	_revalidate (vendor.js:37659)
	invoke (vendor.js:74152)
	flush (vendor.js:74073)
	flush (vendor.js:74225)
	_end (vendor.js:74655)
	end (vendor.js:74458)
	_run (vendor.js:74698)
	(funzione anonima) (vendor.js:163674)
	fire (vendor.js:24559)
	fireWith (vendor.js:24689)
	done (vendor.js:30596)
	(funzione anonima) (vendor.js:30839)
```
Anyone else experiencing this?

Thanks.

### PR DESCRIPTION
**Pull request by buschtoens**
This PR removes all non-essential niceties to reduce bundle size for users that don't use `ember-concurrency` and `ember-decorators`. It also reverts TypeScript back to the oldschool Ember Object Model to enable merging with `ember-engines` / `ember-asset-loader` / Ember core.

Fixes #3. Most likely also fixes #2. 

/cc @villander @dgeb

### CODE REVIEW

File: addon/components/lazy-mount/component.js [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+
+  /**
+   * The following is a really low-fidelity implementation of something that
+   * would be handled by ember-concurrency or ember-lifeline.
+   */
+
+  _threadId: null,
+
+  _thread() {
+    registerWaiter(this, () => !get(this, 'isLoading'));
```
Comment (villander) [inline addon/components/lazy-mount/component.js]: `registerWaiter` don't must be use only to test environment? I'm not sure

File: addon/components/lazy-mount/component.js [hunk 2]
```diff
@@ -0,0 +1,80 @@
+import Component from '@ember/component';
+import { get, set, setProperties } from '@ember/object';
+import { assert } from '@ember/debug';
+import { inject as service } from '@ember/service';
+import { registerWaiter } from '@ember/test';
+import template from './template';
+
+export default Component.extend({
```
Comment (villander) [inline addon/components/lazy-mount/component.js]: I would like see jsdoc here as well, this can help us

File: addon/components/lazy-mount/component.js (hunk 1 above)
Comment (buschtoens) [reply addon/components/lazy-mount/component.js]: AFAIK this is how it's done. If no tests are run, e.g. `checkWaiters` is not called, nothing happens.

https://github.com/emberjs/ember.js/blob/v3.7.0/packages/ember-testing/lib/test/waiters.js

However, it seems that I should call `unregisterWaiter` afterwards, otherwise we would leak memory.

Comment (buschtoens) [reply addon/components/lazy-mount/component.js]: https://github.com/bendemboski/ember-concurrency-test-waiter/blob/master/addon/with-test-waiter.js#L17-L20

Here it's wrapped in `if (Ember.testing)`. I'll wrap as well for good measure. 👍

File: addon/components/lazy-mount/component.js [hunk 3]
```diff
@@ -0,0 +1,195 @@
...
+  _thread() {
+    if (Ember.testing) {
+      registerWaiter(this, () => !get(this, 'isLoading'));
+    }
+
+    const threadId = set(this, '_threadId', {});
+    return () =>
+      get(this, 'isDestroyed') ||
+      get(this, 'isDestroying') ||
+      get(this, '_threadId') !== threadId;
```
Comment (villander) [inline addon/components/lazy-mount/component.js]: @buschtoens I don't understand this line, because it's always will be equal 

`{} !=== {}`

Comment (buschtoens) [reply addon/components/lazy-mount/component.js]: Talked about this on Discord, but for anyone following along at home and also wondering:

Previously `loadEngine` was a restartable ember-concurrency task, meaning that whenever a new instance is started, any old potentially still running instance is cancelled. This is to make sure that, we don't accidentally render stale content, because of async calls, when the input arguments change.

The trick here with `{}` is:

```js
{} === {} // => false

const obj = {};
obj === obj // => true
```

Whenever `loadEngine` is called it starts a new "thread", which then sets `this._threadId` to a new object. So any old still running threads would then compare there own closure `threadId` to the new `this._threadId`, which is then unequal.

Comment (villander) [reply addon/components/lazy-mount/component.js]: sound good, thank you bud
